### ISSUE TITLE
Inconsistency of icons

### ISSUE THREAD

**Issue by davidnoeee** [GymQuiz/beta#3]
We should consider settling on a consistent iconset, I'd propose "Vusesax Icons", I have the full icon set available. Any other suggestions? Maybe check figma community

**Comment by GymQuiz** [comment]
The Vusesax Icons looks good. If you already have them, i would suggest to use them.

**Comment by Benelem12** [comment]
I used the Bootstrap Icons, so they should be somewhat consistent. But we can also use the Vuesax Icons but I am not really sure if they are a big difference to the icons right now.

**Comment by davidnoeee** [comment]
Vuesax icons have a smoother, edgier, more playful look, while the Bootstrap icons are similar to material design icons. :)
